from tools.subtractors import BgSubtractorType

MAX_VIDEO_WIDTH = 640
MAX_VIDEO_HEIGHT = 480

BLUR_SIZE = 21
DELTA_THRESHOLD = 25
MINIMAL_MOVE_AREA = 100
DILATION_ITERATIONS = 2
BG_SUBTRACTOR = BgSubtractorType.KNN
SIGMADELTA_FRAMES = 500

MAX_CONTOURS = 500
MINIMAL_MOVE_FRAMES = 10
MAX_BREAK_LENGTH = 10
