from tools.subtractors import BgSubtractorType

MAX_VIDEO_WIDTH = 640
MAX_VIDEO_HEIGHT = 480

FIRST_REFERENCE_FRAME_INDEX = 1
BLUR_SIZE = 21
DELTA_THRESHOLD = 25
MINIMAL_MOVE_AREA = 100
DILATION_ITERATIONS = 2
REFERENCE_FRAME_REFRESH_FREQUENCY = 100
BG_SUBTRACTOR = BgSubtractorType.KNN

RUNNING_AVG_ALPHA = 0.020
RUNNING_AVG_START_FRAME_NUMBER = 20
